spring:
    data:
        mongodb:
            host: mongo-db
            port: 27017
            database: recipedb
    security:
        user:
            name: vacammar
            password: vacammar
    application:
        name: recipe-api
eureka:
    client:
        serviceUrl:
            defaultZone: http://recipe-discovery:8761/eureka
            instance:
                preferIpAddress: false
logging:
    level:
        org.springframework.web: info
        org.springframework.data: info
