spring:
    security:
        user:
            name: vacammar_security
            password: vacammar_security
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://mysql-db:3306/recipe_security_db
        username: vacammar_security
        password: vacammar_security
    application:
        name: recipe-security
eureka:
    client:
        serviceUrl:
            defaultZone: http://recipe-discovery:8761/eureka/
logging:
    level:
        org.springframework.web: info
        org.springframework.data: info
