#zuul:
#    routes:
#        authentication:
#            path: /api/v1/security/**
#            url: http://recipe-security:8080/api/v1/security
#        recipe:
#            path: /api/v1/recipe/**
#            url: http://recipe-api:8080/api/v1/recipe
#            sensitiveHeaders: Authorization
eureka:
    client:
        serviceUrl:
            defaultZone: http://recipe-discovery:8761/eureka/
spring:
    application:
        name: recipe-gateway
zuul:
    sensitiveHeaders: