server:
    port: 8761
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
spring:
    application:
        name: recipe-discovery
